### ISSUE TITLE
runs on xbox!

### ISSUE THREAD

**Issue by momo-AUX1** [liuk7071/ChonkyStation3#8]
not really an issue, but thought you'd want to know your emulator runs correctly xbox series X|S ! here's a video showing V1 and V2 with patches 

https://github.com/user-attachments/assets/847afe60-5fdf-4eff-b304-d589882b0ccb

https://github.com/user-attachments/assets/bb3e7674-5afa-447a-adad-eccb2b6fa967

If you have a small list of what boots currently I'll be happy to share it with the xbox community, I forgot to fork the code to do a merge but the patched code can be shared with you if you want I changed 4-5 files mainly window, chonky, playstation3 and the RTC clock

**Comment by liuk7071** [comment]
That's pretty cool!

> If you have a small list of what boots currently I'll be happy to share it with the xbox community
If you're talking about games, "ARKEDO SERIES - 03 PIXEL!" is the only fully playable game as of now, so you should try that.

As per your code... I think it's best not to merge it in the main repo, but you should totally create a fork and keep the code there in case anyone might want to try this.

**Comment by momo-AUX1** [comment]
Noted, I'll make the fork and push my code keep up the great work !

**Comment by momo-AUX1** [comment]
FATAL: std::exception
current pc: 0x00307d80


do you know why this happens when booting the game "NPEB00615" ? it tries to do something then rapidly crashes on both MacOS and xbox

**Comment by liuk7071** [comment]
I don't know why on Linux and MacOS the error isn't returned correctly, that's a known issue (instead of just "std::exception" it should give you a meaningful error)

That said, I can try to guess the problem. To boot the game you need to replace the file "key.edat" inside the USRDIR folder of the game with a decrypted version, you can decrypt it in the same way you did for the .sprx files.
Make sure that the decrypted file has the same exact name ("key.edat"), IIRC RPCS3 is going to append ".unedat" to it.

Also, I don't know what you're doing to launch the game but you shouldn't boot the game by passing the path of EBOOT.elf to the executable. You should run ChonkyStation3 without passing any argument and it should show a menu to launch one of the installed games.

**Comment by liuk7071** [comment]
Also, if you are using the latest code, you can try deleting the "spu->step()" line from PlayStation3::step() inside PlayStation3.cpp.
I'm working on implementing the SPUs but they don't work yet and they break things

**Comment by momo-AUX1** [comment]
Alright I'll try doing that and report back if it worked or not thank you for the help !

**Comment by momo-AUX1** [comment]
should the decrypted key be 0kb ? RPCS3 seems to only give that but it did append what you said to it

**Comment by liuk7071** [comment]
It should definitely not be 0kb. Have you verified that the game actually works in RPCS3? Did you install the .rap file in it?

**Comment by liuk7071** [comment]
No idea then, for me the decrypted key is about the same size as the encrypted one

**Comment by liuk7071** [comment]
Maybe check if it gives you any error in the RPCS3 log window

**Comment by momo-AUX1** [comment]
I'll go and check what's breaking where

**Comment by momo-AUX1** [comment]
same issue it seems

installed game as folder from RPCS3 to the Fileystem hdd0 `Found 1 installed games:
[  0] NPEB00615 | ARKEDO SERIES - 03 PIXEL!                | /dev_hdd0/game/NPEB00615 `

it shows a menu to select click index 0 for arkedo 

then it says `FATAL: std::exception 
current pc: 0x00307d80`

fixed the key.edat being 0kb it is now the same size and the content between decrypt and encrypt are different but it's challenging to know what's wrong with so little debug info

**Comment by liuk7071** [comment]
In ChonkyStation3/Common/common.hpp, change
`
throw std::runtime_error(error);
`
to
`
printf(%s\n, error.c_str());
exit(0);
`
and then do the same in the debugAssert function. That should allow it to print the actual error instead of "std::exception"

**Comment by momo-AUX1** [comment]
Object with handle 1800900712 does not exist

**Comment by liuk7071** [comment]
In Dependencies/Panda3DS/logger.hpp, comment out `#define true false` and uncomment `#define false true`

That will enable all the loggers. After you do that send me the full log, it's probably gonna be a bit long

**Comment by momo-AUX1** [comment]
[log.txt](https://github.com/user-attachments/files/19145881/log.txt)

here is the full log

**Comment by liuk7071** [comment]
Are you sure you enabled the loggers like I said earlier? It should print a lot more than that.
Are you perhaps setting up cmake with the -DENABLE_USER_BUILD=ON flag? If so, remove that

**Comment by momo-AUX1** [comment]
it did indeed print more this time and I double checked to not have a user build here is an extended log file 

[log.txt](https://github.com/user-attachments/files/19145947/log.txt)

**Comment by liuk7071** [comment]
Is your fork up to date? I think I know why it breaks, pulling the latest code should fix it

**Comment by liuk7071** [comment]
You might have to delete the spu->step() line I mentioned some messages ago

**Comment by momo-AUX1** [comment]
I did I commented it out 

```c++
void PlayStation3::step() {
    ppu->step();
    //spu->step();
}
```

moon@Mac build % git pull
Already up to date.

unless I'm missing something I updated it an hour ago after I saw you update the SPU

**Comment by momo-AUX1** [comment]
same thing pulled up to latest code from 2 minutes ago, commented out spu step and it still fails saying a certain handle does not exist

**Comment by liuk7071** [comment]
Can you send me what the function "sys_spu_thread_group_create" looks like in ChonkyStation3/OS/Syscalls/sys_spu.cpp ?

**Comment by momo-AUX1** [comment]
```c++
#include <Syscall.hpp>
#include "PlayStation3.hpp"
#include <SPU/SPULoader.hpp>
#include <Lv2Objects/Lv2SPUThreadGroup.hpp>
#include "sys_spu.hpp"


MAKE_LOG_FUNCTION(log_sys_spu, sys_spu);

using namespace sys_spu;

u64 Syscall::sys_raw_spu_create() {
    const u32 id_ptr = ARG0;
    const u32 attr_ptr = ARG1;
    log_sys_spu("sys_raw_spu_create(id_ptr: 0x%08x, attr_ptr: 0x%08x) STUBBED\n", id_ptr, attr_ptr);

    ps3->mem.write<u32>(id_ptr, 0);
    ps3->mem.spu.alloc(SPU_MEM_SIZE);
    
    return Result::CELL_OK;
}

u64 Syscall::sys_spu_thread_group_create() {
    const u32 id_ptr = ARG0;
    const u32 num = ARG1;
    const u32 prio = ARG2;
    const u32 attr_ptr = ARG3;
    log_sys_spu("sys_spu_thread_group_create(id_ptr: 0x%08x, num: %d, prio: %d, attr_ptr: 0x%08x)\n", id_ptr, num, prio, attr_ptr);

    Lv2SPUThreadGroup* group = ps3->lv2_obj.create<Lv2SPUThreadGroup>();
    sys_spu_thread_group_attribute* attr = (sys_spu_thread_group_attribute*)ps3->mem.getPtr(attr_ptr);
    group->attr = attr;

    log_sys_spu("Created SPU thread group \"%s\"\n", group->getName(ps3).c_str());
    ps3->mem.write<u32>(id_ptr, group->handle());

    return Result::CELL_OK;
}

u64 Syscall::sys_spu_thread_initialize() {
    const u32 id_ptr = ARG0;
    const u32 group_id = ARG1;
    const u32 spu_num = ARG2;
    const u32 img_ptr = ARG3;
    const u32 attr_ptr = ARG4;
    const u32 arg_ptr = ARG5;
    log_sys_spu("sys_spu_thread_initialize(id_ptr: 0x%08x, group_id: %d, spu_num: %d, img_ptr: 0x%08x, attr_ptr: 0x%08x, arg_ptr: 0x%08x)\n", id_ptr, group_id, spu_num, img_ptr, attr_ptr, arg_ptr);

    sys_spu_image* img = (sys_spu_image*)ps3->mem.getPtr(img_ptr);
    sys_spu_thread_attribute* attr = (sys_spu_thread_attribute*)ps3->mem.getPtr(attr_ptr);
    sys_spu_thread_argument* arg = (sys_spu_thread_argument*)ps3->mem.getPtr(arg_ptr);
    const auto name = Helpers::readString(ps3->mem.getPtr(attr->name_ptr));
    
    // Create thread and load image
    auto thread = ps3->spu_thread_manager.createThread(name);
    thread->loadImage(img);
    // Setup arguments
    thread->state.gprs[3].dw[1] = arg->arg1;
    thread->state.gprs[4].dw[1] = arg->arg2;
    thread->state.gprs[5].dw[1] = arg->arg3;
    thread->state.gprs[6].dw[1] = arg->arg4;

    // Register this thread in the SPU thread group
    Lv2SPUThreadGroup* group = ps3->lv2_obj.get<Lv2SPUThreadGroup>(group_id);
    group->threads.push_back(thread->id);

    ps3->mem.write<u32>(id_ptr, thread->id);

    return Result::CELL_OK;
}

u64 Syscall::sys_spu_thread_group_start() {
    const u32 group_id = ARG0;
    log_sys_spu("sys_spu_thread_group_start(group_id: %d)\n", group_id);

    Lv2SPUThreadGroup* group = ps3->lv2_obj.get<Lv2SPUThreadGroup>(group_id);
    group->start(ps3);

    return Result::CELL_OK;
}

u64 Syscall::sys_spu_image_import() {
    const u32 image_ptr = ARG0;
    const u32 src = ARG1;
    const u32 size = ARG2;
    const u32 arg4 = ARG3;
    log_sys_spu("sys_spu_image_import(image_ptr: 0x%08x, src: 0x%08x, size: 0x%08x, arg4: 0x%08x) UNIMPLEMENTED\n", image_ptr, src, size);

    Helpers::panic("TODO: sys_spu_image_import syscall\n");
    return Result::CELL_OK;
}

u64 Syscall::sys_spu_thread_group_join() {
    log_sys_spu("sys_spu_thread_group_join() UNIMPLEMENTED\n");

    ps3->thread_manager.getCurrentThread()->status = Thread::ThreadStatus::Sleeping;   // Never wake up
    ps3->thread_manager.getCurrentThread()->reschedule();

    return Result::CELL_OK;
}

u64 Syscall::sys_spu_thread_group_connect_event_all_threads() {
    const u32 id = ARG0;
    const u32 eq = ARG1;
    const u64 req = ARG2;
    const u32 spup_ptr = ARG3;  // spup is u8
    log_sys_spu("sys_spu_thread_group_connect_event_all_threads(id: %d, eq: %d, req: %d, spup_ptr: 0x%08x) UNIMPLEMENTED\n", id, eq, req, spup_ptr);

    ps3->mem.write<u8>(spup_ptr, 0);
    return Result::CELL_OK;
}
```

here it is

**Comment by liuk7071** [comment]
Ok, I dunno what's wrong

Does it give you the same error on both MacOS and Xbox?

**Comment by momo-AUX1** [comment]
yup it gives the same error but the xbox lacks any stdout I'll try building a macOS build with pure unchanged settings and see if it still blows up

**Comment by momo-AUX1** [comment]
```
FATAL: Object with handle 1874993688 does not exist

current pc: 0x00307d80
```

can confirm it still happens on a clean build if someone else who built linux/Mac and tested the game to work it might be how I'm feeding it the game rather than the program

**Comment by momo-AUX1** [comment]
could you try loading a game with an incorrect structure or key.edat and see if it says same?

**Comment by liuk7071** [comment]
No it would give a different error, the game is crashing before it even tries to read key.edat anyway

**Comment by momo-AUX1** [comment]
In that case I'll try building a native windows one and retry tomorrow

**Comment by momo-AUX1** [comment]
FATAL: Object with handle -839117109 does not exist

sub_2b7c8 called from 0x00059e6c
sub_466b8 called from 0x0002b7d8
sub_46700 called from 0x000466d8
sub_44310 called from 0x00046738
sub_451d8 called from 0x00044348
sub_43ef8 called from 0x000451e8
sub_4fcf8 called from 0x00043f18
sub_59c38 called from 0x0004fd1c
sub_29e28 called from 0x00059c88
sub_5d3c0 called from 0x00029e3c
current pc: 0x0005d3e4
PS C:\Users\moon\Documents\chonkyMSVC\ChonkyStation3\buildmsvc\Debug>

happens in powershelgl it seems too

./ChonkyStation3.exe


at this point it's either a PS3 firmware issue, OpenGL issue or a game issue since it seems to work on your machine  


so the same error happens on macOS, Xbox (which is MinGW based) and PC MSVC?????

**Comment by momo-AUX1** [comment]
can you provide me with your PS3 firmware so I can rule that out ?

**Comment by momo-AUX1** [comment]
from the 2 logs It seems the issue might be SPURS donut.elf doesn't seem to load them while ARKEDO tries then fails idk if I'm right tho

**Comment by liuk7071** [comment]
The latest firmware from playstation.com should work fine

**Comment by liuk7071** [comment]
Okay my bad, I forgot that there are a few extra files you need to copy from RPCS3: flashATRAC.pic and flashMP3.pic inside /dev_flash/sys/external. You don't need to decrypt these files. 

This might fix your Windows build, however your MacOS build seemed to crash before attempting to use those files so I don't think that will be fixed.

**Comment by momo-AUX1** [comment]
will test on xbox and windows then report back

**Comment by momo-AUX1** [comment]
can confirm it did fix PC MSVC macOS and xbox mingw have the same problem as before I guess I should just wait for linux support to mature but booting donut.elf on xbox is still great

**Comment by liuk7071** [comment]
I managed to reproduce the issue on my machine, it should be fixed as of the latest commit.

Make sure to still comment out the spu->step line because the game won't work for now if you don't

**Comment by momo-AUX1** [comment]
alright I'll go try it out

**Comment by momo-AUX1** [comment]
it works! the game looks like it renders at double speed but it works

**Comment by momo-AUX1** [comment]
are there any plans to upgrade the file args ? as you said installing it in dev hdd0 works giving it the file path as arg gives a FS error very minor stuff but great work nonetheless I'll go update the mingw fork and see

**Comment by liuk7071** [comment]
Booting individual ELF files (like donut.elf) and booting games works differently, I can't boot the game only given the path of the executable. Which is why you need to copy over the game to dev_hdd0 and let the emulator handle the rest

**Comment by momo-AUX1** [comment]
https://github.com/user-attachments/assets/498e936c-5c96-4de4-9abf-2430dc75d65a

this works so good it almost feels illegal some companies could genuinely use this to port over their PS3 games keep up the GREAT work man !!!!

**Comment by momo-AUX1** [comment]
You can now close this issue if you want or I might use it to highlight any macOS/linux or MinGW issues in the future
